### ISSUE TITLE
Rotate label

### ISSUE THREAD

**Issue by hnguye34** [cleroux/flot.barlabels#4]
Hello,

Is it possible to rotate the label 90° ?
I tried to rotate de context, as following, before/after the call to addText but it does not work.
The angle parameter is not used by Flot so it cannot work neither.

**barLabels.context.rotate(270 * Math.PI / 180);**
barLabels.addText(layer, px, py, text, series.labels.font, angle, width, halign, valign); (Line 146)

Thanks for any idea !

**Comment by cleroux** [comment]
I haven't used flot in several years so I have only tested this on version 0.8.3 which was the last stable version before the new maintainers took over. (v0.8.3 is still available here http://www.flotcharts.org/downloads/ or in the example directory of this repository)

It's unfortunate Flot wasn't updated to support rotated text because it's actually pretty easy.  You will need to modify jquery.flot.js or download the modified version from this repository (Please see the notes I added to the README).

In jquery.flot.js at the end of `Canvas.prototype.AddText()`, add the CSS transform to rotate the text.
```js
        position.element.css({
            top: Math.round(y),
            left: Math.round(x),
            'text-align': halign,
            transform: 'rotate('+angle+'deg)'  // Add this line
        });
```

I have updated this plugin to support the angle option, updated the README and added an example.  

![image](https://user-images.githubusercontent.com/1497949/114825466-1e4f8c00-9d7b-11eb-8cf6-342fb227b548.png)

I hope this helps.  I'm closing this issue since I think this is the best solution I can offer.

**Comment by hnguye34** [comment]
It 's working well. Thank you for your help !

**Comment by hnguye34** [comment]
Reopened by accident
