### ISSUE TITLE
How to show the label outside but at the bottom of the bar, not on top ?

### ISSUE THREAD

**Issue by hnguye34** [cleroux/flot.barlabels#6]
Hi, 

Could you tell me whether it is possible to show the label outside but at the bottom of the bar and not at the top as now ?
I have tried to add this option as following (naming bottom_outside position) but it is not working when y is positive.

```
else if (pos == positions.bottom_outside) {
                            if (y >= 0) {
                                valign = "top";
                                py =  series.yaxis.p2c(b)  + plot.getPlotOffset().bottom;
                            } else {
                                valign = "bottom";
                                py =  series.yaxis.p2c(b) + series.labels.padding;
                            }
```

Thank you for your help

**Comment by cleroux** [comment]
Sorry, I never considered positioning the label at the outside bottom because it would overlap with the axis.  I do not plan to implement such a feature.

I don' use Flot anymore but I'll leave this issue open for now in case I have some time to investigate.

**Comment by cleroux** [comment]
So if I understand correctly, I think this is already supported by Flot's Categories plugin.  See an example here:
http://www.flotcharts.org/flot/examples/categories/index.html

However, if you still want to use this plugin, I had some success with the following changes.

```js
} else if (pos == positions.bottom_outside) {
    if (y >= 0) {
        valign = "top";
        py = pb + series.labels.padding;
    } else {
        valign = "bottom";
        py = pb - series.labels.padding;
    }
}
```

Also comment out this code which serves to keep labels inside the plot area:
```js
/*if (Math.abs((series.yaxis.p2c(0) - series.yaxis.p2c(y))) - series.labels.padding < textInfo.height) {
    pos = positions.outside;
}*/
```

And lastly, just to be thorough, make sure you've added `bottom_outside` to this enum (though I think you probably did this already):
```js
var positions = {
    middle: 0,
    base: 1,
    end: 2,
    outside: 3,
    bottom_outside: 4
};
```

I will not be adding this feature to this plugin since I think it is handled better by Flot.  But I hope this helps anyway.
